format_version: 10
pipelines:
  master-ami:
    group: Terraform
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-36887ae:
        git: https://github.com/Poorna32/master-ami.git
        shallow_clone: false
        auto_update: true
        branch: main
    secure_variables:
      TF_VAR_vault_token: AES:OaIhuO1JgKgmKqlaBDqC1g==:FD3fAzlakILYiUSfLBtimpaDQ1p0IM74HXlOZ8MJB5o=
    stages:
      - DEV:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: false
          environment_variables:
            env: dev
          approval:
            type: manual
          jobs:
            terraform-apply:
              tasks:
              - exec: { command: terraform, arguments: [ "init" ] ,run_if: passed}
              - exec: { command: terraform, arguments: [ "apply", "-auto-approve" ] ,run_if: passed}